// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServerReady():Promise<boolean>;

export function GetExecutableDir():Promise<string>;

export function GetModels():Promise<Array<string>>;

export function StartServer(arg1:string,arg2:string):Promise<void>;

export function StopServer():Promise<void>;
